"""Pydantic schemas for the orchestrator agent."""

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel


class ThreatSummary(BaseModel):
    """A ranked threat from the daily brief."""

    rank: int
    title: str
    agent_source: str
    impact: str
    confidence: float
    action_required: str


class QualityGap(BaseModel):
    """A ranked quality gap from the daily brief."""

    rank: int
    title: str
    agent_source: str
    severity: str
    location: str


class AccelerationOpportunity(BaseModel):
    """A potential schedule acceleration opportunity."""

    title: str
    agent_source: str
    potential_savings_days: int
    cost: float
    description: str


class DailyBriefOutput(BaseModel):
    """The daily briefing generated by the orchestrator."""

    brief_date: date
    generated_at: datetime
    top_threats: list[ThreatSummary]  # exactly 3
    quality_gaps: list[QualityGap]  # exactly 2
    acceleration: AccelerationOpportunity | None = None
    full_text: str


class EscalationEvent(BaseModel):
    """A critical event that triggers immediate PM notification."""

    event_id: str
    trigger_agent: str
    trigger_type: str
    severity: Literal["critical"]
    impact_dollars: float
    safety_critical: bool
    message: str
    sms_sent: bool = False
    timestamp: datetime


class CrossAgentTrigger(BaseModel):
    """A trigger from one agent to invoke another."""

    source_agent: str
    source_event_type: str
    target_agent: str
    target_action: str
    data: dict = {}
    priority: int = 5  # 1=highest, 10=lowest
